# Generated by Django 4.0.3 on 2022-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_work',
            field=models.IntegerField(verbose_name='Проработанное количество часов'),
        ),
    ]
