# Generated by Django 4.0.3 on 2022-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekend_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество выходных'),
        ),
    ]
