# Generated by Django 4.0.3 on 2022-04-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_time_time_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='task_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='app.task', verbose_name='К какому проекту принадлежит'),
            preserve_default=False,
        ),
    ]
