# Generated by Django 3.2.12 on 2022-04-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_time_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager_key',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='manager_user_key', to='app.employee', verbose_name='К какому менеджеру'),
            preserve_default=False,
        ),
    ]
