# Generated by Django 3.2.12 on 2022-05-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_manager_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_task',
            field=models.CharField(default='', max_length=50, verbose_name='Статус выполнения'),
            preserve_default=False,
        ),
    ]
