# Generated by Django 3.2.12 on 2022-05-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_task',
            field=models.CharField(choices=[('Сделано', 'Сделано'), ('В работе', 'В работе'), ('Не сделано', 'Не сделано')], max_length=50, verbose_name='Статус выполнения'),
        ),
    ]
