# Generated by Django 3.2.12 on 2022-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220510_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='media/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
