# Generated by Django 3.2.12 on 2022-05-21 15:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=app.models.Employee.upload, verbose_name='Фотография'),
        ),
    ]
